# Generated by Django 3.2.12 on 2022-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='multipleChoice',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='answer',
            field=models.ManyToManyField(to='courses.Answer'),
        ),
    ]
