# Generated by Django 3.2.12 on 2022-02-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220226_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='answer',
            new_name='answers',
        ),
    ]
