# Generated by Django 3.2.12 on 2022-02-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_answer_multiplechoice_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='name',
        ),
    ]
